import React from 'react';
import { useNavigate } from 'react-router-dom';
import '../home.css';
const Home = () => {
  const navigate = useNavigate();

  const navigateToGrid = () => {
    navigate('/grid');
  };

  const navigateToDashboard = () => {
    navigate('/dashboard');
  };

  return (
    <div>
      <div>
        <div className="container" idName="hero">

            <h2>OUR MISSION</h2>

            <p className="viks"> WildTrack is to protect endangered species using a unique combination of advanced data
                analyses,artificial intelligence,and traditional ecological knowledge.<br></br>WildTrack has developed an
                innovative new model to tackle the global decline in species-using footprints.<br></br> Our
                handsoff,animal-friendly approach also reduces the risk of human:other species transmission of viruses
                and reduces the risk of future pandemics.</p>
        </div>
        </div>
        <div className="container section" idName="services" >
            <h2>Our Services for wild tracking system</h2>

            <div className="map-container">
                <div className="service-list">
                    <div className="service-item">
                        <h3>Animal Tracking collar with Satellite Communication</h3>

                        <ol type="a">
                            <li className="animal">Collar Attachment</li>
                            <li className="animal">Location Acquisition</li>
                            <li className="animal">Data Processing</li>
                            <li className="animal">Data transmission</li>
                            <li className="animal">Data Access</li>

                        </ol>
                        <img src="https://th.bing.com/th/id/R.f94df8d3a2b136e064deadc874db4e13?rik=Qn8BiWfjN4NaAw&riu=http%3a%2f%2fwww.gundogsonline.com%2fImg%2fEstore%2fProducts%2fe1e326d1-ebf4-4104-82c8-739a34bd3a09_14149_Lg.jpg&ehk=sbCfBwUaruhcoZOgiC%2f%2fuwjmMjs%2f9F0nZAgLQsnkeaQ%3d&risl=&pid=ImgRaw&r=0"
                          alt='Coller' className="coller"></img>

                    </div>
                    <div className="service-item">
                        <h3>Monitoring the temperature and orientation:</h3>
                        <p className="animal">Provides behaviour and basic health of animal with the help of temperature
                            sensor.</p>
                        <img src="https://th.bing.com/th/id/R.f079db74fdafae21ecb5825efc4713d8?rik=NirQlM6e8%2fiUFg&riu=http%3a%2f%2fs3.amazonaws.com%2fwestgen%2fwp-content%2fuploads%2f2017%2f03%2f27151505%2fHeatime3.jpg&ehk=JkuqrMepGkmwU4gNPYczvyF3fWPYnywErEmZ3gGGsdw%3d&risl=&pid=ImgRaw&r=0" className="mon"
                            alt="error" ></img>
                    </div>
                    <div className="service-item">
                        <h3>SMS Messages</h3>
                        <p className="animal">If the user sends message "location" to the system then the system
                            provides
                            the
                            location of the animal , acceleration of animal and gives temperature of animal in degree
                            centigrade.</p>

                        <img src="https://th.bing.com/th/id/OIP.XMFLegQgqK9bUDWEBJ-hvwAAAA?w=400&h=400&rs=1&pid=ImgDetMain" alt="sms"className="mon" />
                    </div>
                </div>
            </div>
            <br></br>
            <h2>Behaviour of Animals</h2>

            <p idName="behaviour">1. The wearable wireless sensor system plays a crucial role in providing behavioural and
                physiological data for each individual in precision livestock farming. This article reviewed the most
                types of sensor systems available in the market and summarized detailed information on these systems.
                Additionally, through meta-analysis, the accuracy of the parameters generated by the sensor system was
                verified. As a result, it has been shown that there are more than 60 sensor systems of various types
                have been developed and sold. Most of them generate behavioral and physiological parameters of cattle
                with excellent performance.<br></br>
                2. Smart farming technologies are rapidly being developed due to their
                effectiveness and efficiency in monitoring the health of livestock. Such examples are intelligent
                wearables and biosensor devices that are health monitors or disease detectors. These current 
                development of numerous minimally invasive and compact state-of-the-art devices, the management of
                cattle farms could change in the future.</p>

                <div className="container"idName="about" class="section">
                    <h2>About Us</h2>
                    <p>
                    <ol type="a">
                        <li class="ab">Team Name:Tech Growth</li>
                        <li class="ab">Topic:Wild Track</li>
                    </ol>

                    <h3 className="ab">Team Members:</h3>
                    <ol type="1">
                        <li className="ab">Vaibhav Parab</li>
                        <li className="ab">Vikas Rathod</li>
                        <li className="ab">Shrishail Patil</li>
                        <li className="ab">Omkar Kurane</li>
                    </ol>



                    </p>
                    <a href="https://drive.google.com/file/d/1k5aS7kd06oyrbBvV25ik3NRo0G7Zf8H5/view"><button 
                            className="btn2">click this
                            link to
                            know about our idea.</button></a>
                            <button className="btn2" onClick={navigateToGrid}>Go to Animal Tracking</button>
      <button className="btn2" onClick={navigateToDashboard}>Go to Behavioural Dashboard</button>  

                </div>
                <div class="container" className="section contact">
                    <h2>Contact Us</h2>
                    <p>Get in touch with us for more information or to start a project.</p>
                 
      
                    <form>
                        <input type="text" placeholder="Your Name" required></input>
                        <input type="email" placeholder="Your Email" required></input>
                        <textarea placeholder="Your Message" required></textarea>
                        <button type="submit" class="btn">Send Message</button>
                    </form>
                </div> <footer>
            <div className="container">
                <p>&copy; Thank you for visiting our web page</p>
            </div>
            </footer>
      </div>
    </div>
    
  );
};

export default Home;
